2025-03-11 12:44:01,209 INFO    MainThread:3078 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-11 12:44:01,209 INFO    MainThread:3078 [wandb_setup.py:_flush():67] Configure stats pid to 3078
2025-03-11 12:44:01,209 INFO    MainThread:3078 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-11 12:44:01,209 INFO    MainThread:3078 [wandb_setup.py:_flush():67] Loading settings from /home/duckietown_rl_course/duckiesim/rl/wandb/settings
2025-03-11 12:44:01,209 INFO    MainThread:3078 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-11 12:44:01,210 INFO    MainThread:3078 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250311_124401-te9tdh49/logs/debug.log
2025-03-11 12:44:01,210 INFO    MainThread:3078 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250311_124401-te9tdh49/logs/debug-internal.log
2025-03-11 12:44:01,210 INFO    MainThread:3078 [wandb_init.py:init():761] calling init triggers
2025-03-11 12:44:01,211 INFO    MainThread:3078 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'exp_name': 'ppo', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'DuckieTownRL', 'wandb_entity': None, 'capture_video': False, 'env_id': 'DuckietownDiscrete-v0', 'total_timesteps': 10000000, 'learning_rate': 0.00025, 'num_envs': 1, 'num_steps': 2048, 'anneal_lr': True, 'gamma': 0.99, 'gae_lambda': 0.95, 'num_minibatches': 4, 'update_epochs': 4, 'norm_adv': True, 'clip_coef': 0.05, 'clip_vloss': False, 'ent_coef': 0.05, 'vf_coef': 0.5, 'max_grad_norm': 0.5, 'target_kl': None, 'batch_size': 2048, 'minibatch_size': 512, 'num_iterations': 4882, '_wandb': {'code_path': 'code/duckiesim/rl/ppo.py'}}
2025-03-11 12:44:01,211 INFO    MainThread:3078 [wandb_init.py:init():784] starting backend
2025-03-11 12:44:01,211 INFO    MainThread:3078 [wandb_init.py:init():788] sending inform_init request
2025-03-11 12:44:01,238 INFO    MainThread:3078 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-11 12:44:01,238 INFO    MainThread:3078 [wandb_init.py:init():803] backend started and connected
2025-03-11 12:44:01,242 INFO    MainThread:3078 [wandb_init.py:init():896] updated telemetry
2025-03-11 12:44:01,269 INFO    MainThread:3078 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-11 12:44:01,699 INFO    MainThread:3078 [wandb_init.py:init():995] starting run threads in backend
2025-03-11 12:44:01,831 INFO    MainThread:3078 [wandb_run.py:_console_start():2377] atexit reg
2025-03-11 12:44:01,831 INFO    MainThread:3078 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-11 12:44:01,831 INFO    MainThread:3078 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-11 12:44:01,831 INFO    MainThread:3078 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-11 12:44:01,833 INFO    MainThread:3078 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-11 13:04:09,572 WARNING MsgRouterThr:3078 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-11 13:04:09,573 INFO    MsgRouterThr:3078 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
